todoproject/todoapp/urls.py
from django.urls import path

from todoapp import views
app_name = 'todoapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<int:taskid>', views.delete, name='delete'),
    path('update/<int:taskid>', views.update, name='update'),
    path('cbvhome', views.TaskLV.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/', views.TaskDV.as_view(), name='cbvdetail'),
    path('cbvupdate/<int:pk>/', views.TaskUV.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeV.as_view(), name='cbvdelete'),
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models


# Create your models here.

class Task(models.Model):
    task = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.task

todoproject/todoapp/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy

from todoapp.form import TaskForm
from todoapp.models import Task

# Class View
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView


class TaskLV(ListView):
    model = Task
    template_name = 'index.html'
    context_object_name = 'tasks'


class TaskDV(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'tasks'


class TaskUV(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'tasks'
    fields = ('task', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail', kwargs={'pk': self.object.id})


class TaskDeV(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')


# Function view
def home(request):
    tasks = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(task=name, priority=priority, date=date)
        task.save()
    return render(request, 'index.html', {'tasks': tasks})


def delete(request, taskid):
    task = Task.objects.get(id=taskid)
    if request.method == 'POST':
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, taskid):
    task = Task.objects.get(id=taskid)
    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'f': form, 'task': task})

todoproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ToDo List</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'styles/style.css' %}">
</head>
<body>
  {% block body%}

  {% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div class="movie" style="text-align: center; margin-top: 100px;">
    <form method="POST" >
        {% csrf_token %}
        <h3>Do you want to delete this task?</h3>
        <input type="submit" class="btn btn-warning" value="Yes">
        <a class="btn btn-info" href="{% url 'cbvhome'%}" >No</a>
    </form>
</div>


{% endblock %}

todoproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}



 <div class="col-md-4 card-body shadow " style="margin: 50px auto;">
<h4 class="card-title">{{tasks.task}}</h4>
<p><b>{{tasks.priority}}</b></p>
<p><b>{{tasks.date}}</b></p>
<a class="btn btn-danger" href="{% url 'todoapp:delete' tasks.id %}">Task Done</a>
<a class="btn btn-warning" href="{% url 'todoapp:update' tasks.id %}">Update Task</a>
</div> 
{% endblock %}

todoproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<!-- banner -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- input -->
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form class="p-3 shadow" action="" method="POST" >
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" name="task" placeholder="Enter your Task">
                </div><br>
                <div class="form-group">
                    <input class="form-control" type="text" name="priority" placeholder="Priority">
                </div><br>
                <div class="form-group">
                    <input class="form-control" type="date" name="date" placeholder="Enter Date">
                </div><br>
                    <input type="submit" class="btn btn-success" value="Add Task">
            </form>
        </div>

<!-- output -->
        <div class="col-md-6">
            <h1>Task tobe Completed</h1>
            {% for i in tasks %}
            <div class="card shadow">
                <div class="card-body">
                    <h4 class="card-title">{{i.task}}</h4>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Task Done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">Update Task</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div class="col-md-4 card" style="margin:30px auto; text-align: center;">
    <div class="card-header">
        <div class="card-title">
            <h1>Update Task</h1>
        </div>
        <div class="card-body" style="display: inline-block; margin: auto;">
            <form action="" method="POST" style=" text-align: right;">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success" type="submit">Update</button>
                <a class="btn btn-info" href="{% url 'todoapp:cbvhome'%}" >Cancel</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}